### ISSUE TITLE
Hammr does not run on 64bit CentOS 6.6. machine

### ISSUE THREAD

**Issue by obourdon** [usharesoft/hammr#18]
<pre>
# more /etc/redhat-release 
CentOS release 6.6 (Final)
# uname -a
Linux ws1 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 23:32:49 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
# wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py ; python get-pip.py  ; yum install gcc python-devel libxml2-devel libxslt-devel ; easy_install progressbar==2.3 ; pip install hammr

At this point everything when fine

# hammr -v
Traceback (most recent call last):
  File "/usr/bin/hammr", line 7, in <module>
    import hammr.hammr
  File "/usr/lib/python2.6/site-packages/hammr/hammr.py", line 26, in <module>
    import commands
  File "/usr/lib/python2.6/site-packages/hammr/commands/__init__.py", line 10, in <module>
    from scan import *
  File "/usr/lib/python2.6/site-packages/hammr/commands/scan/scan.py", line 7, in <module>
    import paramiko
  File "/usr/lib/python2.6/site-packages/paramiko/__init__.py", line 64, in <module>
    from transport import SecurityOptions, Transport
  File "/usr/lib/python2.6/site-packages/paramiko/transport.py", line 33, in <module>
    from paramiko import util
  File "/usr/lib/python2.6/site-packages/paramiko/util.py", line 33, in <module>
    from paramiko.common import *
  File "/usr/lib/python2.6/site-packages/paramiko/common.py", line 98, in <module>
    from Crypto import Random
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/__init__.py", line 29, in <module>
    from Crypto.Random import _UserFriendlyRNG
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in <module>
    from Crypto.Random.Fortuna import FortunaAccumulator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in <module>
    import FortunaGenerator
  File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in <module>
    from Crypto.Util.number import ceil_shift, exact_log2, exact_div
  File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in <module>
    if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
</pre>

**Comment by obourdon** [comment]
In fact after a bit more investigation this seems to be due to the fact that on the distribution some old versions of python modules where installed. The following set of commands seems to make everything right:
<pre>
# Remove potentially old and incompatible python module versions
rpm -e --nodeps python-setuptools python-argparse python-lxml python-httplib2 python-crypto
yum install -y gcc python-devel libxml2-devel libxslt-devel
rpm -qa | sort > rpms.txt
wget -q https://raw.github.com/pypa/pip/master/contrib/get-pip.py
python get-pip.py
easy_install progressbar==2.3
pip install hammr 
</pre>

May be we could enforce the versions according to the following infos
<pre>
Python module RPM package Name installed version => currently available version in PyPi
python-argparse 1.2.1 => 1.3.0
python-setuptools 0.6.10 => 18.2
python-lxml 2.2.3 => 3.3.5
python-httplib2 0.7.7 => 0.9
python-crypto  2.0.1 => 2.6.1 
</pre>
