### ISSUE TITLE
error while running hammr 3.7.2-RC1

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#184]
With a 3.7.fp2 AppCenter, a fresh install of hammr 3.7.2-RC1 I have the following error for one of my users.
Note that other users are ok.

[root@58aa7abfa023 ~]# hammr -u alefebvre -a http://10.1.2.132:8080/ufws
Password: 
hammr> info
*** Command not found: info 
hammr> template list
Getting templates for [alefebvre] ...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hammr/commands/template/template.py", line 61, in do_list
    images = self.api.Users(self.login).Images.Getall()
  File "/usr/lib/python2.7/site-packages/uforge/application.py", line 1356, in Getall
    return self._REST('/users/' + str(self._get('Uid')) + '/images', 'GET', body, element_name, streamingResponseFile, **kwargs)
  File "/usr/lib/python2.7/site-packages/uforge/application.py", line 119, in _REST
    return _Objects.parseString(resp.content, True)
  File "/usr/lib/python2.7/site-packages/uforge/application.py", line 44, in parseString
    raise exception
SimpleFacetValueError: Type <class 'uforge.objects.uforge.STD_ANON_17'> enumeration constraint violated by value gb

**Comment by jbremond** [comment]
Hello,

This version is not maintained anymore.

Regards,
Joris
