### ISSUE TITLE
Providing a wrong UForge URL does not provide a nice error message

### ISSUE THREAD

**Issue by jgweir** [usharesoft/hammr#19]
A HTTP 404 is returned when a bad URL is used (which is correct).

Though the error message is cryptic -- guessing that hammr is interpreting the body and not checking the http return code.

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/hammr/commands/template/template.py", line 500, in import_stack
{
    applianceImport = self.api.Users(self.login).Imports.Import(None, None, "true" if isImport else "false", "true" if isForce else "false")
  File "/Library/Python/2.7/site-packages/uforge/application.py", line 1745, in Import
    return self._REST('/users/' + str(self._get('Uid')) + '/imports', 'POST', body, **kwargs)
  File "/Library/Python/2.7/site-packages/uforge/application.py", line 95, in _REST
    raise Exception(_Objects.parseString(content, True))
  File "/Library/Python/2.7/site-packages/uforge/application.py", line 48, in parseString
    raise exception
XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and body, line 1, column 934
```

**Comment by lqueiroga** [comment]
Hi,
Same error with hammr-3.6:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hammr/commands/user/user.py", line 38, in do_info
    user = self.api.Users(self.login).Get()
  File "/usr/lib/python2.7/site-packages/uforge/application.py", line 195, in Get
    return self._REST('/users/' + str(self._get('Uid')) + '', 'GET', body, element_name, streamingResponseFile, **kwargs)
  File "/usr/lib/python2.7/site-packages/uforge/application.py", line 103, in _REST
    raise Exception(_Objects.parseString(resp.content, True))
  File "/usr/lib/python2.7/site-packages/uforge/application.py", line 30, in parseString
    raise exception
SAXParseException: <unknown>:1:49: syntax error

**Comment by AliceAlbano** [comment]
This issue was corrected by a fix in the SDK python.
