### ISSUE TITLE
How to specify URL for source field in bundle - files.

### ISSUE THREAD

**Issue by MaxTakahashi** [usharesoft/hammr#22]
Hi,

I would like to use URL for source field in bundle - files when importing a template.
But UForge returns an error.

```
[root@localhost tmp]# hammr template import --file archive.tar.gz
Importing template from [archive.tar.gz] archive ...
100%|##############################|
ERROR: Template import: Unknown server error. Please contact UForge support.
```
Server side log:
```
-bash-4.1# cat oar_applianceimport_job4.stdout
2015-04-28 08:54:29 WARN  DbManager:109 - LONG DB INSTRUCTION 2.782 secs init (com.usharesoft.db.DbAccess>>DbAccess.java:init:43)

2015-04-28 08:54:29 INFO  InstanceImportObject:114 - Status: 1% done. Unpackaging import archive
2015-04-28 08:54:30 INFO  InstanceImportObject:227 - (cd /tmp/USER_DATA/FactoryContainer/users/k_takahashi/imports/4/uploads/extracted_archive; /bin/tar xvzf ../import_archive)
2015-04-28 08:54:30 INFO  InstanceImportObject:270 - Creating appliance : test
2015-04-28 08:54:30 INFO  InstanceImportObject:308 - appliance parent URI : users/k_takahashi
2015-04-28 08:54:30 INFO  InstanceImportObject:114 - Status: 20% done. Preliminary check
2015-04-28 08:54:30 INFO  InstanceImportObject:463 - SELECT ap_id from UserCreatedAppliances as a where login='k_takahashi' AND appliance='test' AND version='1.0'
2015-04-28 08:54:30 INFO  InstanceImportObject:519 - SELECT d.* from  Distributions as d where CONCAT(name,' ',version)='CentOS 6' AND arch='x86_64'
2015-04-28 08:54:30 INFO  InstanceImportObject:530 - ditribution name = CentOS 6
2015-04-28 08:54:31 INFO  InstanceImportObject:648 - SELECT db_id from PkgGroups where distrib_id='0' AND name='test-work' AND version='1.0' AND uri like 'users/k_takahashi/%'
2015-04-28 08:54:32 ERROR MySoftwareService:148 - File not found for Pkg: file:/tmp/USER_DATA/FactoryContainer/users/k_takahashi/imports/4/uploads/extracted_archive/http:/repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-2.2.1-1.el6.x86_64.rpm
2015-04-28 08:54:32 ERROR InstanceImportObject:300 - com.usharesoft.services.exceptions.UForgeException: java.io.FileNotFoundException: /tmp/USER_DATA/FactoryContainer/users/k_takahashi/imports/4/uploads/extracted_archive/http:/repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-2.2.1-1.el6.x86_64.rpm (No such file or directory)
2015-04-28 08:54:32 ERROR InstanceImportObject:170 - Setting import error : Unknown server error. Please contact UForge support.
2015-04-28 08:54:32 ERROR InstanceImportObject:188 - Impossible to rollback appliance
java.lang.NullPointerException
        at com.usharesoft.services.InstallProfilesService.delete(InstallProfilesService.java:198)
        at com.usharesoft.services.InstallProfilesService.delete(InstallProfilesService.java:180)
        at com.usharesoft.services.AppliancesService.deleteAppliance(AppliancesService.java:250)
        at com.usharesoft.services.AppliancesService.deleteAppliance(AppliancesService.java:187)
        at com.usharesoft.distrotools.InstanceImportObject.setImportError(InstanceImportObject.java:183)
        at com.usharesoft.distrotools.InstanceImportObject.importObject(InstanceImportObject.java:302)
        at com.usharesoft.distrotools.cmds.ImportExportEnv.main(ImportExportEnv.java:62)
2015-04-28 08:54:32 INFO  InstanceImportObject:840 - Do cleanup
```

Could you please show me how to use URL value for the source filed in bundle - files?
http://hammr.io/?page_id=835

Hereunder is what I did:
* export a template.
* extract the archive and replace "source" value from native path to URL in template.json file.
```
# cat template.json
...
    "bundles" : [ {
...
      "files" : [ {
        "name" : "zabbix-2.2.2-1.el6.x86_64.rpm",
        "source" : "http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-2.2.1-1.el6.x86_64.rpm"
```
* tar the files except bundle files.
* import the archive.

**Comment by usharesoft** [comment]
Hi,

Hammr support URL in bundles, logo, scripts with the template creation command, and not import.
The difference is the following:
When you use import, it is based on a tar archive and hammr assume the archive is correct (all bin file are present).
When you use create, hammr read the json file, search for URL references, download binaries, and create a coherent archive and then upload it (import) to UForge.

**Comment by MaxTakahashi** [comment]
Hi,

Thank you very much for the information.
I have succeeded to use URL for importing templates.

Thanks.
