### ISSUE TITLE
hammr image publish to Outscale raises an error

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#225]
```
# hammr image publish --id 525 -c credentials209.json --file builderAno.yml
you provided a yaml file, checking...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hammr/commands/image/image.py", line 161, in do_publish
    self.publish_builder(builder, template, appliance, rInstallProfile, 1, image)
  File "/usr/lib/python2.7/site-packages/hammr/commands/image/image.py", line 401, in publish_builder
    mypImage = publishMethod(builder)
TypeError: publish_outscale() takes exactly 2 arguments (1 given)
```
[builderAno.yml.zip](https://github.com/usharesoft/hammr/files/1035976/builderAno.yml.zip)

**Comment by Numerinico** [comment]
Fixed in #333
