### ISSUE TITLE
The API end point for factory.usharesoft.com has been changed?

### ISSUE THREAD

**Issue by MaxTakahashi** [usharesoft/hammr#29]
Hi,

Hammr returns an error when I use "/ufws-3.3" for the api end point according to the guide.
http://hammr.io/?page_id=528

```
# hammr os list --url https://factory.usharesoft.com:443/ufws-3.3 -u user -p xxx
Getting distributions for [xxx] ...
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/hammr/commands/os/os.py", line 35, in do_list
    distributions = self.api.Users(self.login).Distros.Getall(None, None)
  File "/usr/lib/python2.6/site-packages/uforge/application.py", line 1549, in Getall
    return self._REST('/users/' + str(self._get('Uid')) + '/distros', 'GET', body, **kwargs)
  File "/usr/lib/python2.6/site-packages/uforge/application.py", line 95, in _REST
    raise Exception(_Objects.parseString(content, True))
  File "/usr/lib/python2.6/site-packages/uforge/application.py", line 48, in parseString
    raise exception
XMLSyntaxError: Opening and ending tag mismatch: HR line 1 and body, line 1, column 946
```

The command has been succeeded with "/api" for the API end point.

hammr version '0.2.5.2'

Thanks.

**Comment by usharesoft** [comment]
Hello,

On UForge Now, the web service is available only with this url:
https://uforge.usharesoft.com/api (or https://factory.usharesoft.com/api)

The /ufws-3.3 is not longer accessible on UForge Now. I will update hammr.io examples according to this change.

Thanks
Joris
