### ISSUE TITLE
"hammr scan delete" deletes every scan if scan id and scan instance id is the same.

### ISSUE THREAD

**Issue by MaxTakahashi** [usharesoft/hammr#31]
Hi,

"hammr scan delete" deletes every scans if the same scan id and scan instance id exist in a user.

For example, in the example below, id of scan instance "test9" and scan "test1 Scan #1" is the same (112)

```
hammr> scan list
Getting scans for [dev1] ...
+-----+-----------------------+--------+-----------------+
| Id  |         Name          | Status |  Distribution   |
+=====+=======================+========+=================+
| 104 | test1                 |        | CentOS 6 x86_64 |
+-----+-----------------------+--------+-----------------+
| 112 |         test1 Scan #1 | Done   |                 |
+-----+-----------------------+--------+-----------------+
| 106 | test3                 |        | CentOS 6 x86_64 |
+-----+-----------------------+--------+-----------------+
| 114 |         test3 Scan #1 | Done   |                 |
+-----+-----------------------+--------+-----------------+
| 115 |         test3 Scan #2 | Done   |                 |
+-----+-----------------------+--------+-----------------+
| 107 | test4                 |        | CentOS 6 x86_64 |
+-----+-----------------------+--------+-----------------+
| 116 |         test4 Scan #1 | Done   |                 |
+-----+-----------------------+--------+-----------------+
| 108 | test5                 |        | CentOS 6 x86_64 |
+-----+-----------------------+--------+-----------------+
| 117 |         test5 Scan #1 | Done   |                 |
+-----+-----------------------+--------+-----------------+
| 109 | test6                 |        | CentOS 6 x86_64 |
+-----+-----------------------+--------+-----------------+
| 118 |         test6 Scan #1 | Done   |                 |
+-----+-----------------------+--------+-----------------+
| 110 | test7                 |        | CentOS 6 x86_64 |
+-----+-----------------------+--------+-----------------+
| 119 |         test7 Scan #1 | Done   |                 |
+-----+-----------------------+--------+-----------------+
| 111 | test8                 |        | CentOS 6 x86_64 |
+-----+-----------------------+--------+-----------------+
| 120 |         test8 Scan #1 | Done   |                 |
+-----+-----------------------+--------+-----------------+
| 112 | test9                 |        | CentOS 6 x86_64 |
+-----+-----------------------+--------+-----------------+
| 121 |         test9 Scan #1 | Done   |                 |
+-----+-----------------------+--------+-----------------+

Found 8 scans
```

Delete scan with id 112. An exception was returned.
```
hammr> scan delete --id 112
Searching scan with id [112] ...
+-----+-------+--------+-----------------+
| Id  | Name  | Status |  Distribution   |
+=====+=======+========+=================+
| 112 | test9 |        | CentOS 6 x86_64 |
+-----+-------+--------+-----------------+

Do you really want to delete scan with id 112 [Y/n]
Y
Please wait...
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/hammr/commands/scan/scan.py", line 430, in do_delete
    self.api.Users(self.login).Scannedinstances(doArgs.id).Delete()
  File "/usr/lib/python2.6/site-packages/uforge/application.py", line 2232, in Delete
    return self._REST('/users/' + str(self._get('Uid')) + '/scannedinstances', 'DELETE', body, **kwargs)
  File "/usr/lib/python2.6/site-packages/uforge/application.py", line 93, in _REST
    resp, content = obj._client.request(fullUrl, method.upper(), body = body, headers = requestHttpHeader)
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 1291, in _conn_request
    response = conn.getresponse()
  File "/usr/lib64/python2.6/httplib.py", line 990, in getresponse
    response.begin()
  File "/usr/lib64/python2.6/httplib.py", line 391, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.6/httplib.py", line 349, in _read_status
    line = self.fp.readline()
  File "/usr/lib64/python2.6/socket.py", line 433, in readline
    data = recv(1)
  File "/usr/lib64/python2.6/ssl.py", line 215, in recv
    return self.read(buflen)
  File "/usr/lib64/python2.6/ssl.py", line 136, in read
    return self._sslobj.read(len)
SSLError: The read operation timed out
None
```

No scans exist after launching the "hammr scan delete" command.
Every scans are deleted.
```
hammr> scan list
Getting scans for [dev1] ...
No scans available
```

Thanks

**Comment by obourdon** [comment]
Fixed in my forked version or Hammr + new UForge Python SDK, pull request has been submitted

**Comment by jbremond** [comment]
Thanks for the fix.

Regards,
Joris
