### ISSUE TITLE
"hammr image puglish" returns an exception when template.json includes Japanese characters.

### ISSUE THREAD

**Issue by MaxTakahashi** [usharesoft/hammr#35]
Hi,

"hammr image puglish" returns exception when template.json includes Japanese characters in "builder" - "description".

Here is how to reproduce this issue.

- create template.json
```
{
  "stack" : {
    "name" : "MyTemplate",
    "version" : "1.0",
    "description": "これはhammrを使って作成したテンプレートです。",
    "os" : {
      "name" : "RedHat Enterprise Linux",
      "version" : "6.5",
      "arch" : "x86_64",
      "profile" : "Minimal",
      "pkgs": [
        {
          "name": "curl"
        },
        {
          "name": "file"
        },
        {
          "name": "tar"
        },
        {
          "name": "wget"
        },
        {
          "name": "which"
        }
      ]
    },
    "installation" : {
      "keyboard": "jp106",
      "timezone": "Asia/Tokyo",
      "diskSize": 12288,
      "swapSize": 512
    }
  },
  "builders": [
    {
      "type": "openstack-qcow2",
      "account": {
        "type": "openstack",
        "name": "test",
        "endpoint": "http://test:9292",
        "keystoneEndpoint": "http://test:5000/v2.0",
        "username": "user",
        "password": "password"
      },
      "tenant": "maximizedev",
      "imageName": "myTemplate",
      "description": "OpenStack配信テスト"
    }
  ]
}
```
- create template, build image.
```
hammr template create --file template.json
hammr template build --file template.json
```
- publish the image. Hammr returns an exception.
```
[root@hammr-351 templates]# hammr image publish --file template.json
Validating the template file [template.json] ...
OK: Syntax of template file [template.json] is ok
Publishing 'openstack-qcow2' image (1/1)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/hammr/commands/image/image.py", line 147, in do_publish
    rCode = self.publish_builder(builder, template, appliance, rInstallProfile, i, None)
  File "/usr/lib/python2.6/site-packages/hammr/commands/image/image.py", line 409, in publish_builder
    rpImage = self.api.Users(self.login).Appliances(appliance.dbId).Images(comliantImage.dbId).Pimages().Publish(mypImage)
  File "/usr/lib/python2.6/site-packages/uforge/application.py", line 820, in Publish
    return self._REST('/users/' + str(self._get('Uid')) + '/appliances/' + str(self._get('Aid')) + '/images/' + str(self._get('Itid')) + '/pimages', 'POST', body, **kwargs)
  File "/usr/lib/python2.6/site-packages/uforge/application.py", line 93, in _REST
    resp, content = obj._client.request(fullUrl, method.upper(), body = body, headers = requestHttpHeader)
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 1258, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 914, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.6/httplib.py", line 954, in _send_request
    self.send(body)
  File "/usr/lib64/python2.6/httplib.py", line 759, in send
    self.sock.sendall(str)
  File "/usr/lib64/python2.6/ssl.py", line 200, in sendall
    amount = len(data)
TypeError: object of type 'publishImage' has no len()
```

Thanks.

**Comment by jbremond** [comment]
This problem was fixed globally (all input field) inside the uforge_python_sdk. (new version available)

I can closed the bug
