### ISSUE TITLE
image list returns error enumeration constraint violated by value Etc/UTC

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#411]
This was encountered on hammr 3.8.4.
```
hammr> image list
INFO: Getting all images and publications for [alefebvre] ...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hammr/commands/image/image.py", line 58, in do_list
    images = self.get_all_images()
  File "/usr/lib/python2.7/site-packages/hammr/commands/image/image.py", line 527, in get_all_images
    images = self.api.Users(self.login).Images.Getall()
  File "/usr/lib/python2.7/site-packages/uforge/application.py", line 1506, in Getall
    return self._REST('/users/' + str(self._get('Uid')) + '/images', 'GET', body, element_name, streamingResponseFile, **kwargs)
  File "/usr/lib/python2.7/site-packages/uforge/application.py", line 120, in _REST
    return _Objects.parseString(resp.content, True)
  File "/usr/lib/python2.7/site-packages/uforge/application.py", line 45, in parseString
    raise exception
SimpleFacetValueError: Type <class 'uforge.objects.uforge.STD_ANON_16'> enumeration constraint violated by value Etc/UTC
```

**Comment by alefebvr** [comment]
Note that this error occurs if the user has an image build from a template where the time zone is "UTC(Etc/UTC )".
Also the same error occurs with the "template list" command.
Time zones which produce this error include (I haven't tried them all):
- UTC(Etc/UTC )
- UCT(Etc/UCT )
- Zulu(Etc/Zulu )

**Comment by AliceAlbano** [comment]
Fix should most likely be inside uforge product : Have a strict supported list of timezone or no predefined values ?

**Comment by CanutMIAGE** [comment]
This bug has been fixed (modified some values uforge.xsd).
