### ISSUE TITLE
Builder for OVF

### ISSUE THREAD

**Issue by bastienmartin** [usharesoft/hammr#416]
When trying to build a template with the builder from the documentation http://docs.usharesoft.com/projects/hammr/en/latest/pages/machine-images/builders/builders-ovf.html, the following error is displayed:

```
INFO: Checking default credentials file...
INFO: no username provided on command line, trying credentials file
INFO: Using credentials file: /root/.hammr/credentials.yml
you provided a yaml file, checking the syntax...
INFO: You provided a yaml file, checking...
Generating 'OVF or OVA' image (1/1)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hammr/commands/template/template.py", line 434, in do_build
    myimage,myinstallProfile = func(myimage, builder, myinstallProfile, self.api, self.login)
  File "/usr/lib/python2.7/site-packages/hammr/utils/generate_utils.py", line 138, in generate_ovf
    installProfile.hwType = builder["hardwareSettings"]["hwType"]
  File "/usr/lib64/python2.7/site-packages/pyxb/binding/basis.py", line 98, in __setattr__
    return super(_TypeBinding_mixin, self).__setattr__(name, value)
  File "/usr/lib64/python2.7/site-packages/pyxb/binding/content.py", line 1043, in set
    value = self.__elementBinding.compatibleValue(value, is_plural=self.isPlural())
  File "/usr/lib64/python2.7/site-packages/pyxb/binding/basis.py", line 1629, in compatibleValue
    return self.typeDefinition()._CompatibleValue(value, **kw)
  File "/usr/lib64/python2.7/site-packages/pyxb/binding/basis.py", line 425, in _CompatibleValue
    raise pyxb.SimpleTypeValueError(cls, value)
SimpleTypeValueError: Type {http://www.w3.org/2001/XMLSchema}string cannot be created from: 7
```

**The YAML file**
```
---
stack:
  name: PSTAS-69
  version: '1.0'
  installation:
    internetSettings: basic
    diskSize: 12288
    swapSize: 512
  os:
    name: CentOS
    version: '7'
    arch: x86_64
    profile: Minimal
builders:
- type: OVF or OVA
  hardwareSettings:
    memory: 1024
    hwType: 7
```

**Comment by AliceAlbano** [comment]
Fixed by #429
