### ISSUE TITLE
hammr template list fails with "enumeration constraint violated by value sdi"

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#448]
Hello,
Using hammr 3.8.6, hammr template list returns the following error.
I don't know of any work around.
```
hammr> template list
Getting templates for [zeus] ...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hammr/commands/template/template.py", line 56, in do_list
    appliances = self.api.Users(self.login).Appliances().Getall()
  File "/usr/lib/python2.7/site-packages/uforge/application.py", line 447, in Getall
    return self._REST('/users/' + str(self._get('Uid')) + '/appliances', 'GET', body, element_name, streamingResponseFile, **kwargs)
  File "/usr/lib/python2.7/site-packages/uforge/application.py", line 120, in _REST
    return _Objects.parseString(resp.content, True)
  File "/usr/lib/python2.7/site-packages/uforge/application.py", line 45, in parseString
    raise exception
SimpleFacetValueError: Type <class 'uforge.objects.uforge.STD_ANON_10'> enumeration constraint violated by value sdi
```

**Comment by alefebvr** [comment]
After investigation, this seems related to an issue in UForge scan which produces invalid partitioning layout (in other words, we should never have an advanced partitioning such as the one in the template coming from scan import). Let us first investigate on the UForge scan side and put this hammr issue on hold.

**Comment by alefebvr** [comment]
This issue is linked to an internal AppCenter issue (aka UFORGE-11862). 
Let us close this ticket for now, and we can open a new one if a similar issue appears in hammr for other valid partitioning layouts.
