### ISSUE TITLE
"hammr image publish" returns exception if there is no cloud account.

### ISSUE THREAD

**Issue by MaxTakahashi** [usharesoft/hammr#46]
Hi,

"hammr image publish" command returns exception if there is no cloud account registered.

- command result:
```
[root@hammr-351 templates]# hammr image publish --file fj3.json
INFO: no username nor password provided on command line, trying credentials file
INFO: Using credentials file: /root/.hammr/credentials.json
INFO: Using url https://myforge/api
Validating the template file [fj3.json] ...
OK: Syntax of template file [fj3.json] is ok
Publishing 'openstack-qcow2' image (1/1)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/hammr/commands/image/image.py", line 147, in do_publish
    rCode = self.publish_builder(builder, template, appliance, rInstallProfile, i, None)
  File "/usr/lib/python2.6/site-packages/hammr/commands/image/image.py", line 391, in publish_builder
    if accounts is None or not accounts.get_credAccount():
AttributeError: 'str' object has no attribute 'get_credAccount'
```

- config json:
```
...
  "builders": [
    {
      "type": "openstack-qcow2",
      "account": {
        "type": "openstack",
        "name": "myaccount"
      },
      "tenant": "dev",
      "imageName": "myTemplate",
      "description": "OpenStack pub test"
    }
  ]
}
```

- Hammr returns an appropriate message if there is any account.
```
[root@hammr-351 templates]# hammr image publish --file fj3.json
INFO: no username nor password provided on command line, trying credentials file
INFO: Using credentials file: /root/.hammr/credentials.json
INFO: Using url https://myforge/api
Validating the template file [fj3.json] ...
OK: Syntax of template file [fj3.json] is ok
Publishing 'openstack-qcow2' image (1/1)
ERROR: No accounts available with name myaccount
```

Thanks.

**Comment by MaxTakahashi** [comment]
This issue has been fixed in 0.2.5.10.
Thanks Dimitri-San. We can close this issue.
