### ISSUE TITLE
some http errors exit hammr cli instead of retrying the command

### ISSUE THREAD

**Issue by jbremond** [usharesoft/hammr#59]
I was doing a 'hammr template build' and I get this error (maybe due to network packet lost or something like this), and hammr does not retry the "get status" command:

```
Traceback (most recent call last):>>>>>>>>>>>>>>>>>>>>>>                                  | 62%: Installing distri... |                                  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  File "/usr/lib/python2.7/site-packages/hammr-0.2.5.9-py2.7.egg/hammr/commands/template/template.py", line 420, in do_build
    status = self.api.Users(self.login).Appliances(myAppliance.dbId).Images(rImage.dbId).Status.Get()
  File "build/bdist.linux-x86_64/egg/uforge/application.py", line 889, in Get
    return self._REST('/users/' + str(self._get('Uid')) + '/appliances/' + str(self._get('Aid')) + '/images/' + str(self._get('Itid')) + '/status', 'GET', body, **kwargs)
  File "build/bdist.linux-x86_64/egg/uforge/application.py", line 93, in _REST
    resp, content = obj._client.request(fullUrl, method.upper(), body = body, headers = requestHttpHeader)
  File "/usr/lib/python2.7/site-packages/httplib2-0.9-py2.7.egg/httplib2/__init__.py", line 1593, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/site-packages/httplib2-0.9-py2.7.egg/httplib2/__init__.py", line 1335, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/site-packages/httplib2-0.9-py2.7.egg/httplib2/__init__.py", line 1291, in _conn_request
    response = conn.getresponse()
  File "/usr/lib64/python2.7/httplib.py", line 1055, in getresponse
    raise ResponseNotReady()
ResponseNotReady
```

**Comment by AliceAlbano** [comment]
I tried with a small timeout, and the cli hammr was never exited. There is no retry policy in hammr tool for now, I think if we want one, we need to open a new issue with a tag improvement about that.
