### ISSUE TITLE
Dependency error at runtime

### ISSUE THREAD

**Issue by jbremond** [usharesoft/hammr#60]
When you have installed both uforge-python-sdk 3.5.1.x and uforge-python-sdk 3.6.x, and you use a hammr version which require `uforge_python_sdk>=3.5.1.3, <3.6`, there is an error at runtime.
Hammr try to last the newer version of uforge-python-sdk instead of the one describe in the require field of setup.py:

```
Traceback (most recent call last):
  File "/usr/bin/hammr", line 7, in <module>
    import hammr.hammr
  File "/usr/lib/python2.7/site-packages/hammr/hammr.py", line 32, in <module>
    import commands as cmds
  File "/usr/lib/python2.7/site-packages/hammr/commands/__init__.py", line 3, in <module>
    from account import *
  File "/usr/lib/python2.7/site-packages/hammr/commands/account/account.py", line 7, in <module>
    from hammr.utils import *
  File "/usr/lib/python2.7/site-packages/hammr/utils/generics_utils.py", line 13, in <module>
    from uforge.objects.xsd0 import *
ImportError: No module named xsd0
```

**Comment by jgweir** [comment]
This should no longer occur as hammr versioning has been reworked.
