### ISSUE TITLE
Problem converting python object to XML

### ISSUE THREAD

**Issue by sohnoun** [usharesoft/hammr#88]
The converting bug is due to The __ExpandedName_ attribute, which is null in some objects that :
- Are a list of objects  (Certificates)
- Are an element of an Extended object (CredAccount.certificates)

```
Problem converting python object to XML
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hammr-0.3.0.0-py2.7.egg/hammr/commands/account/account.py", line 126, in do_create
    self.api.Users(self.login).Accounts.Create(body=myCredAccount, element_name="ns1:credAccount")
  File "build/bdist.linux-x86_64/egg/uforge/application.py", line 398, in Create
    return self._REST('/users/' + str(self._get('Uid')) + '/accounts', 'POST', body, element_name, **kwargs)
  File "build/bdist.linux-x86_64/egg/uforge/application.py", line 77, in _REST
    body = body.toxml(encoding="utf-8", bds=bds, element_name=element_name)
  File "/usr/lib/python2.7/site-packages/PyXB-1.2.4-py2.7.egg/pyxb/binding/basis.py", line 541, in toxml
    dom = self.toDOM(bds, element_name=element_name)
  File "/usr/lib/python2.7/site-packages/PyXB-1.2.4-py2.7.egg/pyxb/binding/basis.py", line 513, in toDOM
    self._toDOM_csc(bds, element)
  File "/usr/lib/python2.7/site-packages/PyXB-1.2.4-py2.7.egg/pyxb/binding/basis.py", line 2661, in _toDOM_csc
    content.elementDeclaration.toDOM(dom_support, parent, content.value)
  File "/usr/lib/python2.7/site-packages/PyXB-1.2.4-py2.7.egg/pyxb/binding/content.py", line 1100, in toDOM
    dom_support.addAttribute(element, pyxb.namespace.XMLSchema_instance.createExpandedName('type'), value._ExpandedName)
  File "/usr/lib/python2.7/site-packages/PyXB-1.2.4-py2.7.egg/pyxb/utils/domutils.py", line 423, in addAttribute
    element.setAttributeNS(ns_uri, name, self.valueAsText(value))
  File "/usr/lib/python2.7/site-packages/PyXB-1.2.4-py2.7.egg/pyxb/utils/domutils.py", line 403, in valueAsText
    assert value is not None
AssertionError
```

**Comment by segalaj** [comment]
Hello,
Could you please add some steps to reproduce the issue you describe.
Thanks

**Comment by AliceAlbano** [comment]
To be reopened with steps to reproduce if it still happens
